homepage: "https://openquantumsafe.org/"
language: c
primary_contact: ""
auto_ccs:
  - nathaniel.brough@gmail.com
main_repo: "https://github.com/open-quantum-safe/liboqs.git"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
